<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-09-20T04:33:02Z" name="TestNG Session Test Automation Suite" finished-at="2018-09-20T04:33:08Z" duration-ms="5814">
    <groups>
    </groups>
    <test started-at="2018-09-20T04:33:02Z" name="ViewHistory" finished-at="2018-09-20T04:33:08Z" duration-ms="5814">
      <class name="com.qa.testcases.TestHistoryViewProduct">
        <test-method is-config="true" signature="init()[pri:0, instance:com.qa.testcases.TestHistoryViewProduct@5f683daf]" started-at="2018-09-20T04:33:02Z" name="init" finished-at="2018-09-20T04:33:07Z" duration-ms="5089" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="historyViewProduct()[pri:0, instance:com.qa.testcases.TestHistoryViewProduct@5f683daf]" started-at="2018-09-20T04:33:07Z" name="historyViewProduct" finished-at="2018-09-20T04:33:07Z" duration-ms="7" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.qa.pageobject.HomePage.<init>(HomePage.java:31)
at com.qa.testcases.TestHistoryViewProduct.historyViewProduct(TestHistoryViewProduct.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- historyViewProduct -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.testcases.TestHistoryViewProduct@5f683daf]" started-at="2018-09-20T04:33:07Z" name="tearDown" finished-at="2018-09-20T04:33:08Z" duration-ms="713" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.testcases.TestHistoryViewProduct -->
    </test> <!-- ViewHistory -->
  </suite> <!-- TestNG Session Test Automation Suite -->
</testng-results>
